### PR TITLE
Fix #52 (binding to static object) and #53 (Actions updating after Trigger)

### LINKED ISSUE #52: Can't use static object binding with DataTriggerBehavior
If a DataTriggerBehavior is bound with `{Binding ..., Source={x:Static ...}}`, the OnValueChanged call happens before AttachedValue is set. As a result, the actions are never called. I tried saving the event and calling it again in `OnAttached()`, but at this point the Value property on any ChangePropertyActions has not been set, so it still fails.

Example code (in BehaviorsTestApplication):
DataTriggerBehaviorControl.xaml
```
    <Grid RowDefinitions="5*,*">
        <Rectangle Name="DataTriggerRectangle" Grid.Row="0" Margin="5" Stroke="{DynamicResource GrayBrush}" StrokeThickness="5">
            <i:Interaction.Behaviors>
                <ia:DataTriggerBehavior Binding="{Binding ., Source={x:Static vm:MainWindowViewModel.TestInt}}" 
                                        ComparisonCondition="GreaterThan" Value="50">
                    <ia:ChangePropertyAction PropertyName="Fill" TargetObject="{Binding #DataTriggerRectangle}" Value="{DynamicResource YellowBrush}" />
                </ia:DataTriggerBehavior>
                <ia:DataTriggerBehavior Binding="{Binding ., Source={x:Static vm:MainWindowViewModel.TestInt}}" ComparisonCondition="LessThanOrEqual" Value="50">
                    <ia:ChangePropertyAction PropertyName="Fill" TargetObject="{Binding #DataTriggerRectangle}" Value="{DynamicResource BlueBrush}" />
                </ia:DataTriggerBehavior>
            </i:Interaction.Behaviors>
        </Rectangle>
        <StackPanel Grid.Row="1" Margin="5,0,5,5" HorizontalAlignment="Center" VerticalAlignment="Center" Orientation="Horizontal">
            <TextBlock Width="50" VerticalAlignment="Center" Foreground="{DynamicResource GrayBrush}" Text="{Binding ., Source={x:Static vm:MainWindowViewModel.TestInt}}" />
        </StackPanel>
    </Grid>
```
MainWindowViewModel.cs
```
public static int TestInt = 51;
```
Result:
image

The binding correctly updates the TextBox, but does not trigger the DataTriggerBehavior.

### LINKED ISSUE #53: Issue when binding DataTrigger and ChangePropertyAction.Value to same object
When a DataTrigger and ChangePropertyAction are bound to the same object, the DataTrigger will call the ChangePropertyAction before the binding on the ChangePropertyAction has a chance to update.

Example code: (Button increments SelectedCount)
```
        <Button Name="Button" Command="{Binding OnClicked}" Content="{Binding SelectedCount}"/>
        <TextBlock Grid.Row="1">
            <i:Interaction.Behaviors>
                <ia:DataTriggerBehavior Binding="{Binding SelectedCount}" Value="0">
                    <ia:ChangePropertyAction Value="No items selected" PropertyName="Text"/>
                </ia:DataTriggerBehavior>
                <ia:DataTriggerBehavior Binding="{Binding SelectedCount}" Value="1">
                    <ia:ChangePropertyAction Value="1 item selected" PropertyName="Text"/>
                </ia:DataTriggerBehavior>
                <ia:DataTriggerBehavior Binding="{Binding SelectedCount}" Value="1" ComparisonCondition="GreaterThan">
                    <ia:ChangePropertyAction PropertyName="Text">
                        <ia:ChangePropertyAction.Value>
                            <Binding Path="SelectedCount" StringFormat="{}{0} items selected"/>
                        </ia:ChangePropertyAction.Value>
                    </ia:ChangePropertyAction>
                </ia:DataTriggerBehavior>
            </i:Interaction.Behaviors>
        </TextBlock>
```
Result:
Screenshot from 2020-10-20 02-41-11
Screenshot from 2020-10-20 02-41-27
Screenshot from 2020-10-20 02-41-38
Screenshot from 2020-10-20 02-41-48

### PR DESCRIPTION
**Pull request by ThereGoesMySanity**
When a DataTriggerBehavior is bound to a non-static property, the order of initialization looks something like this:

```
Trigger properties defined in XAML (each calls OnValueChanged) -> Action properties defined in XAML (doesn't call OnValueChanged) -> DataContext (calls OnValueChanged)
```

However, when a static binding is used, the order of initialization becomes:

```
Static binding (calls OnValueChanged) -> Trigger properties defined in XAML (each calls OnValueChanged) -> Action properties defined in XAML (doesn't call OnValueChanged)
```

The important thing to note is that the last thing initialized in the latter case doesn't call OnValueChanged -- because of this, none of the triggers are properly invoked in this case.

To fix this, I added listeners to the ActionsCollection so that all properties of any attached Actions also cause an OnValueChanged call. This also fixes #53, since that was caused by bindings of Actions updating after Triggers were invoked.

Fixes #52 
Fixes #53 

EDIT: Sometimes AttachedObject is initialized last as well, so there needs to be a call to OnValueChanged in `OnAttached()` as well.

### CODE REVIEW

**Comment by ThereGoesMySanity** [comment]
Nevermind - this doesn't do what I thought it did.

**Comment by ThereGoesMySanity** [comment]
Updated - this now works properly.

**Comment by Tenjim** [comment]
Hi, 

There is any update of this PR? 

Thank in advance,

**Comment by wieslawsoltes** [comment]
Conflicts with master branch

**Pull request closed without merging**
